# Generated by Django 4.2.19 on 2025-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('class_name', models.CharField(db_column='class', default='1', max_length=10, verbose_name='班级')),
                ('description', models.TextField(blank=True, default='', verbose_name='个人描述')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('status', models.BooleanField(choices=[(True, '在读'), (False, '毕业')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'Student',
            },
        ),
    ]
