# Generated by Django 4.2.19 on 2025-04-16 03:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),  # 修改依赖的迁移文件名
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@example.com', unique=True, verbose_name='电子邮件'),
        ),
    ]