# Generated by Django 4.2.19 on 2025-04-16 03:40

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
        ('student', '0003_alter_student_email'),
    ]

    operations = [
        # 合并操作会自动处理，这里不需要手动添加 operations
    ]