# Generated by Django 4.2.19 on 2025-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='来源平台')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
            ],
        ),
    ]
